<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference
      Include="..\..\src\ResxGen.Generators\ResxGen.Generators.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
    <ProjectReference
      Include="..\..\src\ResxGen.Fixers\ResxGen.Fixers.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="**\*.resx" />
    <CompilerVisibleProperty Include="MSBuildProjectDirectory" />
  </ItemGroup>
</Project>
