using System.Text;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using Pneuma.Localization.Resx.Generators;

namespace Pneuma.Localization.UnitTests;

public class ResxGeneratorTests
{
    [Test]
    public async Task TestGenerator()
    {
        var generatorTest = new CSharpSourceGeneratorTest<ResxSourceGenerator, DefaultVerifier>()
        {
            TestCode = """
                namespace TestProject;

                public class Hello;
                """,
        };

        // stub out the Localization stuff just so it compiles
        generatorTest.TestState.Sources.Add(
            (
                "/home/user/projects/test/Localization/Types.cs",
                SourceText.From(
                    """
                    namespace Microsoft.Extensions.Localization;

                    public interface IStringLocalizer;

                    public interface IStringLocalizer<out T>
                    {
                        LocalizedString this[string name] { get; }
                    }

                    public readonly struct LocalizedString;
                    """,
                    Encoding.UTF8
                )
            )
        );

        generatorTest.TestState.AdditionalFiles.Add(
            (
                "/home/user/projects/test/Resources/Hello.resx",
                SourceText.From(
                    """
                    <?xml version="1.0" encoding="utf-8"?>
                    <root>
                      <data name="Hello" xml:space="preserve">
                        <value>Hello</value>
                      </data>
                      <data name="Hello world" xml:space="preserve">
                        <value>Hello World</value>
                      </data>
                      <data name="123 do re mi" xml:space="preserve">
                        <value>i'm just looking for stupid stuff now</value>
                      </data>
                    </root>
                    """,
                    Encoding.UTF8
                )
            )
        );

        generatorTest.TestState.AnalyzerConfigFiles.Add(
            (
                "/home/user/projects/test/.globalconfig",
                SourceText.From(
                    """
                    is_global = true

                    build_property.RootNamespace = TestProject
                    build_property.MSBuildProjectDirectory = /home/user/projects/test
                    """,
                    Encoding.UTF8
                )
            )
        );

        generatorTest.TestState.GeneratedSources.Add(
            (
                typeof(ResxSourceGenerator),
                "GeneratedFromResxFileAttribute.g.cs",
                SourceText.From(
                    """
                    // <auto-generated />
                    #nullable enable

                    namespace Pneuma.Localization;

                    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
                    internal sealed class GeneratedFromResxFileAttribute(string path) : global::System.Attribute
                    {
                        public string Path => path;
                    }

                    """,
                    Encoding.UTF8
                )
            )
        );

        generatorTest.TestState.GeneratedSources.Add(
            (
                typeof(ResxSourceGenerator),
                "HelloStringLocalizerExtensions.g.cs",
                SourceText.From(
                    """
                    // <auto-generated />
                    #nullable enable

                    namespace TestProject;

                    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                    [global::Pneuma.Localization.GeneratedFromResxFile("Resources/Hello.resx")]
                    public static class HelloStringLocalizerExtensions
                    {
                        extension(global::Microsoft.Extensions.Localization.IStringLocalizer<global::TestProject.Hello> localizer)
                        {
                            /// <summary>
                            ///  Gets a string like 'Hello' as a <see cref="global::Microsoft.Extensions.Localization.LocalizedString" />
                            /// </summary>
                            public global::Microsoft.Extensions.Localization.LocalizedString Hello => localizer["Hello"];

                            /// <summary>
                            ///  Gets a string like 'Hello World' as a <see cref="global::Microsoft.Extensions.Localization.LocalizedString" />
                            /// </summary>
                            public global::Microsoft.Extensions.Localization.LocalizedString Hello_world => localizer["Hello world"];

                            /// <summary>
                            ///  Gets a string like 'i&apos;m just looking for stupid stuff now' as a <see cref="global::Microsoft.Extensions.Localization.LocalizedString" />
                            /// </summary>
                            public global::Microsoft.Extensions.Localization.LocalizedString _123_do_re_mi => localizer["123 do re mi"];
                        }
                    }

                    """,
                    Encoding.UTF8
                )
            )
        );

        await generatorTest.RunAsync().ConfigureAwait(false);
    }
}
